// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWEvMMG9gXMq_AgBmnbxVZGczakgk-7VA',
    appId: '1:999665064318:web:ffc43199bc86f2dc2ffb2f',
    messagingSenderId: '999665064318',
    projectId: 'tourism-app-belajarubic',
    authDomain: 'tourism-app-belajarubic.firebaseapp.com',
    storageBucket: 'tourism-app-belajarubic.appspot.com',
    measurementId: 'G-HKR40N356V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Eusk241n8DG_xVxnxWll4_3WvOS5XgY',
    appId: '1:999665064318:android:1527b4da9c0cb00e2ffb2f',
    messagingSenderId: '999665064318',
    projectId: 'tourism-app-belajarubic',
    storageBucket: 'tourism-app-belajarubic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwLfVsrWxh6dLj6d7Rg3NhgFJfBQZE5kQ',
    appId: '1:999665064318:ios:12871a44d844bd542ffb2f',
    messagingSenderId: '999665064318',
    projectId: 'tourism-app-belajarubic',
    storageBucket: 'tourism-app-belajarubic.appspot.com',
    iosBundleId: 'com.example.tourismApp',
  );
}
